#!/usr/bin/env sh

# see this wiki page for information:
#  https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Ensure there are at least 7 spaces
current_spaces=$(yabai -m query --spaces | jq 'length')
while [ $current_spaces -lt 7 ]; do
    yabai -m space --create
    current_spaces=$((current_spaces + 1))
done

# global settings

yabai -m config window_placement             second_child
yabai -m config window_topmost               off

yabai -m config window_border                off
yabai -m config window_shadow                off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config window_animation_duration    0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0

yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# Mouse support
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off

yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config top_padding                  0
yabai -m config window_gap                   0


# Setup preferences on spaces

# general space settings
yabai -m config layout                       bsp
yabai -m config --space 1 layout             stack
yabai -m config --space 3 layout             bsp
yabai -m config --space 5 layout             stack

# Space labels
yabai -m space 1 --label "Misc" --display 1
yabai -m space 2 --label "Code" --display 2
yabai -m space 3 --label "Browser" --display 2
yabai -m space 4 --label "Social" --display 2
yabai -m space 5 --label "Business" --display 2
yabai -m space 6 --label "Perso" --display 2

# Misc
yabai -m rule --add app="Finder" space="Misc"
yabai -m rule --add app="Spotify" space="Misc"
yabai -m rule --add app="Youtube Music Desktop App" space="Misc"
yabai -m rule --add app="Activity Monitor" space="Misc"
yabai -m rule --add app="Bitwarden" space="Misc"
yabai -m rule --add app="Notion" space="Misc"
yabai -m rule --add app="Cron" space="Misc"
yabai -m rule --add app="Calendar" space="Misc"
yabai -m rule --add app="FaceTime" space="Misc"
yabai -m rule --add app="App Store" space="Misc"

# Browser
yabai -m rule --add app="Firefox" space="Browser"
yabai -m rule --add app="Chromium" space="Browser"
yabai -m rule --add app="Safari" space="Browser"
yabai -m rule --add app="Arc" pace="Browser"

# Programming
yabai -m rule --add app="Alacritty" space="Code"
yabai -m rule --add app="Terminal" space="Code"
yabai -m rule --add app="iTerm2" space="Code"

# Social
yabai -m rule --add app="Discord" space="Social"
yabai -m rule --add app="Slack" space="Social"
yabai -m rule --add app="Messages" space="Social"
yabai -m rule --add app="Messenger" space="Social"

# Business
yabai -m rule --add app="Spark" space="Business"
yabai -m rule --add app="Microsoft Excel" space="Business"

# manage off list:
yabai -m rule --add label="Raycast" app="Raycast" manage=off
yabai -m rule --add label="System Preferences" app="System Preferences" manage=off
yabai -m rule --add label="System Settings" app="System Settings" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add title=".*Appel.*avec" manage=off space="Misc"
yabai -m rule --add label="Arc" title="Shortcuts" manage=off
yabai -m rule --add label="Arc" title="Little Arc.*" manage=off
yabai -m rule --add label="FaceTime" app="FaceTime" manage=off

# --- Events ---

# Make all non-resizable window float (https://github.com/koekeishiya/yabai/issues/1317)
yabai -m signal --add event=window_created action='yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er ".\"can-resize\" or .\"is-floating\"" || yabai -m window $YABAI_WINDOW_ID --toggle float'

echo "yabai configuration loaded.."
