#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

#!/usr/bin/env sh

# global settings

yabai -m config window_placement             second_child
yabai -m config window_topmost               off

yabai -m config window_border                off
yabai -m config window_shadow                off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.9

yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# Mouse support
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off

# general space settings
yabai -m config layout                       bsp
yabai -m config --space 1 layout             float
yabai -m config --space 3 layout             float

yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config top_padding                  0
yabai -m config window_gap                   0


# Setup preferences on spaces

# Space labels
yabai -m space 1 --label "Misc"
yabai -m space 2 --label "Code"
yabai -m space 3 --label "Browser"
yabai -m space 4 --label "Social"

# Misc
yabai -m rule --add app="Finder" space="Misc"
yabai -m rule --add app="Spotify" space="Misc"
yabai -m rule --add app="Activity Monitor" space="Misc"
yabai -m rule --add app="Bitwarden" space="Misc"
yabai -m rule --add app="Notion" space="Misc"
yabai -m rule --add app="Cron" space="Misc"
yabai -m rule --add app="Calendar" space="Misc"
yabai -m rule --add app="FaceTime" space="Misc"

# Browser
yabai -m rule --add app="Brave" space="Browser"

# Programming
yabai -m rule --add app="Alacritty" space="Code"
yabai -m rule --add app="Terminal" space="Code"
yabai -m rule --add app="iTerm2" space="Code"

# Social
yabai -m rule --add app="Discord" space="Social"
yabai -m rule --add app="Slack" space="Social"
yabai -m rule --add app="Spark" space="Social"
yabai -m rule --add app="Messages" space="Social"

# Make all non-resizable window float (https://github.com/koekeishiya/yabai/issues/1317)
yabai -m signal --add event=window_created action='yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er ".\"can-resize\" or .\"is-floating\"" || yabai -m window $YABAI_WINDOW_ID --toggle float'

yabai -m signal --add event=window_created label="Misc" action='yabai -m window --toggle zoom-fullscreen'

echo "yabai configuration loaded.."
