fail_fast: false

repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks
  - repo: local
    hooks:
      - id: stylua-check
        name: stylua --check (nvim config)
        language: system
        entry: stylua --check nvim/
        files: ^nvim/.*\.lua$
        pass_filenames: false
