return false -- better use vtsls (not sure in fact...)

-- local preferences = {
--   autoImportFileExcludePatterns = {
--     "**/components/**/*.vue",
--   },
-- }
-- return {
--   init_options = {
--     preferences = preferences,
--     plugins = {
--       {
--         name = "@vue/typescript-plugin",
--         location = require("mason-registry").get_package("vue-language-server"):get_install_path()
--           .. "/node_modules/@vue/language-server",
--         languages = { "vue" },
--       },
--     },
--   },
--   filetypes = { "typescript", "javascript", "javascriptreact", "typescriptreact", "vue" },
--   on_attach = function(client, _)
--     -- formatting is done by prettier and eslint
--     client.server_capabilities.document_formatting = false
--   end,
-- }
