#!/bin/sh

usage() {
	cat <<\EOF
usage: ag-jump <mode> <pattern>

Jump to interesting elements in an editor.
The <mode> parameter is one of:

grep: elements are grep hits. Arguments are given to grep.

EOF
}

open_editor() {
	editor=vim
	eval "$editor -q \$1"
}

mode_grep() {
	ag --ignore-dir build/ --no-color --no-group "$@" |
	perl -pe '
	s/[ \t]+/ /g;
	s/^ *//;
	'
}

if test $# -lt 1; then
	usage >&2
	exit 1
fi
mode=$1; shift

trap 'rm -f "$tmp"' 0 1 2 3 15
tmp=`mktemp -t ag-jump.XXXXXX` || exit 1
type "mode_$mode" >/dev/null 2>&1 || { usage >&2; exit 1; }
"mode_$mode" "$@" >"$tmp"
test -s "$tmp" || exit 0
open_editor "$tmp"
