#!/bin/sh

usage() {
	cat <<\EOF
usage: hg-jump <mode> [<args>]

Jump to interesting elements in an editor.
The <mode> parameter is one of:

grep: elements are grep hits. Arguments are given to grep.

EOF
}

open_editor() {
	editor=vim
	eval "$editor -q \$1"
}

# Grep -n generates nice quickfix-looking lines by itself,
# but let's clean up extra whitespace, so they look better if the
# editor shows them to us in the status bar.
mode_grep() {
	hg grep -n "$@" |
	perl -pe '
	s/[ \t]+/ /g;
	s/^ *//;
	'
}

if test $# -lt 1; then
	usage >&2
	exit 1
fi
mode=$1; shift

trap 'rm -f "$tmp"' 0 1 2 3 15
tmp=`mktemp -t hg-jump.XXXXXX` || exit 1
type "mode_$mode" >/dev/null 2>&1 || { usage >&2; exit 1; }
"mode_$mode" "$@" >"$tmp"
test -s "$tmp" || exit 0
open_editor "$tmp"
